name: Build Caddy Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
  repository_dispatch:
    types:
      - build

env:
  IMAGE_NAME: gera2ld/caddy

jobs:
  build-caddy:
    permissions:
      contents: read
      # packages: write # Needed if pushing to GitHub Container Registry

    runs-on: ubuntu-latest

    if: ${{ github.event.client_payload.version || github.event.inputs.version }}

    steps:
      - name: Check version
        run: |
          echo Preparing version: $VERSION
          if curl -fs https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$VERSION > /dev/null; then
            echo WARNING: Version exists: $VERSION
          fi
          echo VERSION=$VERSION >> $GITHUB_ENV
        env:
          VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Caddy
        run: |
          export CADDY_VERSION=v$VERSION
          GOARCH=amd64 ./build.sh
          GOARCH=arm64 ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin

  build-docker:
    needs: build-caddy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.architecture }} Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: gera2ld/caddy:latest,gera2ld/caddy:${{ env.VERSION }}
          build-args: CADDY_VERSION=${{ env.VERSION }}
        env:
          VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
