name: Build Caddy Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
  repository_dispatch:
    types:
      - build

env:
  IMAGE_NAME: gera2ld/caddy

jobs:
  build:
    permissions:
      contents: read
      # packages: write # Needed if pushing to GitHub Container Registry

    strategy:
      matrix:
        include:
          - architecture: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - architecture: arm64
            runner: [self-hosted, linux, ARM64]
            platform: linux/arm64

    runs-on: ${{ matrix.runner }}

    if: ${{ github.event.client_payload.version || github.event.inputs.version }}

    steps:
      - name: Check version
        run: |
          echo Preparing version: $VERSION
          if curl -fs https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$VERSION > /dev/null; then
            echo WARNING: Version exists: $VERSION
          fi
          echo VERSION=$VERSION >> $GITHUB_ENV
        env:
          VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.architecture }} Image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ matrix.architecture }}

  create_manifest:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # packages: write # Needed if pushing to GitHub Container Registry

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Multi-Architecture Manifest
        run: |
          # Define the image tags for each architecture built in the previous jobs
          AMD64_TAG=${{ env.IMAGE_NAME }}:${{ env.VERSION }}-amd64
          ARM64_TAG=${{ env.IMAGE_NAME }}:${{ env.VERSION }}-arm64

          # Create the manifest list
          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            ${AMD64_TAG} \
            ${ARM64_TAG}

          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:latest \
            ${AMD64_TAG} \
            ${ARM64_TAG}

          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        env:
          VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
